spring:
  application:
    name: wise-task-plugin
  datasource:
    url: jdbc:postgresql://${DB}:5432/${PLUGIN_DB}
    username: ${PLUGIN_DB_USER}
    password: ${PLUGIN_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          use_streams_for_binary: false


path-plugin: ${PLUGIN_PATH}
plugin-validation-limit: ${PLUGIN_VALIDATION_LIMIT}

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
  level:
    org.hibernate: ${LOGGING_LEVEL}
    ru.leti.wise.task.plugin: ${LOGGING_LEVEL}

grpc:
  service:
    graph:
      port: ${GRAPH_GRPC_PORT}
      host: ${GRAPH_APP_NAME}
  port: ${PLUGIN_GRPC_PORT}
server:
  port: ${PLUGIN_PORT}

management:
  tracing:
    sampling:
      probability: 1
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  zipkin:
    tracing:
      endpoint: http://${TEMPO_HOST}:${TEMPO_PORT}/api/v2/spans
